FROM mcr.microsoft.com/dotnet/sdk:9.0.100-noble

# Arguments
ARG username=ubuntu
ARG path=/development

# Environment variables
ENV USER=${username}
ENV USERNAME=${username}

LABEL org.opencontainers.image.source="https://github.com/solairen/password_generator"
LABEL org.opencontainers.image.description="Development image"
LABEL org.opencontainers.image.authors="Michał Oleszek solairen@solairen.tech"
LABEL org.opencontainers.image.licenses=MIT
LABEL release=development

# User root user
USER root

RUN apt update && apt -y install wget git gnupg && apt autoremove openssh-server -y && apt clean \
  && mkdir ${path} \
  # Install starship
  && curl -o /tmp/install.sh https://starship.rs/install.sh \
  && sh /tmp/install.sh -y \
  && mkdir /home/${username}/.config \
  && starship preset no-empty-icons -o /home/${username}/.config/starship.toml \
  && echo "[terraform]" >> /home/${username}/.config/starship.toml \
  && echo "format = '([(\$version | workspace: \$workspace)](\$style))'" >> /home/${username}/.config/starship.toml \
  && echo "eval '$(starship init bash)'" >> /home/${username}/.bashrc \
  # Cleanup
  && rm /tmp/install.sh

# Use developer user
USER ${username}

ENTRYPOINT [ "bash" ]
