name: Docker registry
on:
  workflow_dispatch:
    inputs:
      version:
        description: Set docker image version.
        required: true

env:
  VERSION: ${{ github.event.inputs.version }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push with tag latest
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            moleszek/password-generator:latest
            moleszek/password-generator:${{ env.VERSION }}
            ghcr.io/solairen/password-generator:latest
            ghcr.io/solairen/password-generator:${{ env.VERSION }}
