name: Docker registry
on:
  workflow_dispatch:
    inputs:
      version:
        description: Set docker image version.
        required: true

env:
  DISCORD: ${{ secrets.discord_webhook }}
  VERSION: ${{ github.event.inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}
      - name: Build and push with tag latest
        uses: docker/build-push-action@v2
        with:
          file: Docker/Dockerfile
          push: true
          tags: moleszek/password-generator:latest
      - name: Build and push with custom tag
        uses: docker/build-push-action@v2
        with:
          file: Docker/Dockerfile
          push: true
          tags: moleszek/password-generator:${{ env.VERSION }}
  notify_on_success:
    name: Send notification on success
    needs:
      - build
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          description: "Successfully build and push docker image to dockerhub"
  notify_on_failure:
    name: Send notification on failure
    needs:
      - test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          status: failure
          description: "Failed to build and push docker image to dockerhub!"
