name: Docker registry
on:
  workflow_dispatch:
    inputs:
      version:
        description: Set docker image version.
        required: true

env:
  VERSION: ${{ github.event.inputs.version }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}
      - name: Build and push with tag latest
        uses: docker/build-push-action@v6
        with:
          file: Docker/Dockerfile
          push: true
          tags: moleszek/password-generator:latest
      - name: Build and push with custom tag
        uses: docker/build-push-action@v6
        with:
          file: Docker/Dockerfile
          push: true
          tags: moleszek/password-generator:${{ env.VERSION }}
