name: Test docker image
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    container: docker:stable
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build dockerfile
        run: docker build -t password-generator -f Docker/Dockerfile .
