name: Test docker image
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

env:
  DISCORD: ${{ secrets.discord_webhook }}

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker:stable
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.token }}
      - name: Build dockerfile
        run: docker build -t password-generator -f Docker/Dockerfile .
  notify_on_success:
    name: Send notification on success
    needs:
      - test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          description: "Successfully build docker image"
  notify_on_failure:
    name: Send notification on failure
    needs:
      - test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          status: failure
          description: "Failed to build docker image!"
