---
name: Unit test
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

permissions:
  contents: read

jobs:
  test:
    name: Run test
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout ${{ github.repository }} repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run test
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: "9.0.x"
    - run: dotnet test test/test.csproj
