name: Test docker image
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push with tag latest
      uses: docker/build-push-action@v6
      with:
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: |
          moleszek/password-generator:test
          ghcr.io/solairen/password-generator:test
